seed: 42
cv:
  n_splits: 5
  shuffle: True
  random_state: 42

xgb:
  params:
    objective: "binary:logistic"
    eval_metric: "logloss"
    use_label_encoder: false
  default_grid:
    n_estimators: [100, 200]
    max_depth: [3, 6]
    learning_rate: [0.1, 0.01]
    subsample: [1.0, 0.8]

lgb:
  params:
    objective: "binary"
    metric: "binary_logloss"
  default_grid:
    n_estimators: [100, 200]
    max_depth: [-1, 6]
    learning_rate: [0.1, 0.01]
    num_leaves: [31, 64]
